name = "intervals-wellness-worker"
main = "src/index.js"
compatibility_date = "2025-11-11"

# TÃ¤glich um 03:17 UTC (entspricht i.d.R. 04:17/05:17 in Deutschland je nach Sommerzeit)
triggers = { crons = ["0 20 * * *", "0 6 * * *"] }

[[kv_namespaces]]
binding = "KV"
id = "ID"
preview_id = "preview_id"
