name = "intervals-icu-netlify"
main = "src/index.js"
compatibility_date = "2025-11-11"

# Abendlicher WÃ¤chter alle 30 Min im Abendfenster (UTC) + morgendlicher Fixlauf.
triggers = { crons = ["*/30 15-22 * * *", "0 6 * * *"] }

[[kv_namespaces]]
binding = "KV"
id = "95402760eee9445fa98df09aad54cdfc"
preview_id = "95402760eee9445fa98df09aad54cdfc"
