name = "intervals-icu-netlify"
main = "src/index.js"
compatibility_date = "2025-11-11"

# Zweimal t√§glich: morgens 06:00 UTC und abends 19:00 UTC
# (Deutschland: i.d.R. 07:00/08:00 und 20:00/21:00 je nach Sommerzeit)
triggers = { crons = ["0 19 * * *", "0 6 * * *"] }

[[kv_namespaces]]
binding = "KV"
id = "95402760eee9445fa98df09aad54cdfc"
preview_id = "95402760eee9445fa98df09aad54cdfc"
